# Set the behaviour of the API depending of the URL which makes the request
# name - Service name to be displayed in the swagger docs
# description - Header description to be displayed in the swagger docs
# accession - Accession example to be displayed in the swagger docs
# collection - Specific collection to be targeted. Other collections will be filtered away
# global - Set if it is to behave as global API instead of a local (federated) API
# production - Set if projects with 'published: false' are to be hidden (true) or shown (false)

hosts:
    
    localhost:
        name: MDposit (local)
        description: The main server including all simulations
        accession: A0001

    mdposit.mddbr.eu:
        name: MDposit
        description: The main server including all simulations
        accession: MD-A00001
        global: true
        production: true

    mdposit-dev.mddbr.eu:
        name: MDposit
        description: The main server including all simulations
        accession: MD-A00001
        global: true

    mdposit-dev.bsc.es:
        name: MDposit (obsolete)
        description: The main server including all simulations
        accession: MD-A00001

    bioexcel-cv19.bsc.es:
        name: BioExcel-CV19
        description: The Covid-19 server
        accession: MCV1900193
        collection: cv19
        production: true

    bioexcel-cv19-dev.bsc.es:
        name: BioExcel-CV19
        description: The Covid-19 server
        accession: MCV1900193
        collection: cv19

    model-cns-dev.bsc.es:
        name: MoDEL-CNS
        description: The Central Nervous System server
        collection: mcns

    abc-dev.mddbr.eu:
        name: ABC
        description: The ABC server
        accession: seq001
        collection: abc # This is redundant with the current implementation

    abc.mddbr.eu:
        name: ABC
        description: The ABC server
        accession: seq001
        collection: abc # This is redundant with the current implementation
        production: true

    mmb-dev.mddbr.eu:
        name: MMB node
        description: The MMB federated node server
        accession: A0001

    mmb.mddbr.eu:
        name: MMB node
        description: The MMB federated node server
        accession: A0001
        production: true

    oxford-dev.mddbr.eu:
        name: Oxford node
        description: The Oxford University federated node server
        accession: A01M3

    oxford.mddbr.eu:
        name: Oxford node
        description: The Oxford University federated node server
        accession: A01M3
        production: true

    cineca.mddbr.eu:
        name: Cineca node
        description: The Cineca federated node server at Bologna
        accession: A0005

    jsc.mddbr.eu:
        name: JSC node
        description: The JSC federated node server at Jülich
        accession: A0001