const { Worker } = require('worker_threads');

const PDB_CONTENT = `
REMARK    GENERATED BY TRJCONV
TITLE     Gyas ROwers  Atre At Cryogenic Speed t= 100.00000
REMARK    THIS IS A SIMULATION BOX
CRYST1  145.220  145.220  129.101  90.00  90.00  90.00 P 1           1
MODEL        1
ATOM      1  N   LYS A   1      58.360  73.770 102.780  1.00  0.00           N
ATOM      2  H1  LYS A   1      58.680  74.340 103.530  1.00  0.00           H
ATOM      3  H2  LYS A   1      57.500  73.300 102.970  1.00  0.00           H
ATOM      4  H3  LYS A   1      59.080  73.080 102.640  1.00  0.00           H
ATOM      5  CA  LYS A   1      58.370  74.570 101.540  1.00  0.00           C
ATOM      6  CB  LYS A   1      59.810  75.010 101.330  1.00  0.00           C
ATOM      7  CG  LYS A   1      60.070  76.140 100.330  1.00  0.00           C
ATOM      8  CD  LYS A   1      59.560  77.510 100.780  1.00  0.00           C
ATOM      9  CE  LYS A   1      59.860  78.630  99.770  1.00  0.00           C
ATOM     10  NZ  LYS A   1      59.150  79.850 100.180  1.00  0.00           N
ATOM     11  HZ1 LYS A   1      59.710  80.620  99.900  1.00  0.00           H
ATOM     12  HZ2 LYS A   1      58.340  79.920  99.620  1.00  0.00           H
ATOM     13  HZ3 LYS A   1      58.880  79.870 101.150  1.00  0.00           H
ATOM     14  C   LYS A   1      57.880  73.820 100.310  1.00  0.00           C
ATOM     15  O   LYS A   1      58.110  72.620 100.210  1.00  0.00           O
ATOM     16  N   GLU A   2      57.190  74.570  99.450  1.00  0.00           N
ATOM     17  H   GLU A   2      57.040  75.550  99.550  1.00  0.00           H
ATOM     18  CA  GLU A   2      56.530  74.000  98.260  1.00  0.00           C
ATOM     19  CB  GLU A   2      55.180  74.680  98.060  1.00  0.00           C
ATOM     20  CG  GLU A   2      55.430  76.090  97.520  1.00  0.00           C
ATOM     21  CD  GLU A   2      55.680  77.120  98.630  1.00  0.00           C
ATOM     22  OE1 GLU A   2      54.700  77.670  99.180  1.00  0.00           O
ATOM     23  OE2 GLU A   2      56.860  77.340  98.930  1.00  0.00           O
ATOM     24  C   GLU A   2      57.410  73.760  97.030  1.00  0.00           C
ATOM     25  O   GLU A   2      58.020  74.700  96.520  1.00  0.00           O
TER
ENDMDL
`.trim();

const getAtomsIndicesFor = (pdbFile, selection) =>
  new Promise((resolve, _reject) => {
    const fakeData = Buffer.from(PDB_CONTENT, 'utf-8');
    // const view = new Uint8Array(fakeData.buffer);
    // console.log(fakeData, view);
    const worker = new Worker('./worker.js');
    worker.postMessage({ type: 'init', file: fakeData, selection: '_N' });
    // console.log('main thread', view.buffer);
    // console.log(fakeData);
    worker.addListener('message', message => {
      console.log(message);
      worker.unref();
      worker.terminate();
      resolve(message);
    });
  });

module.exports = getAtomsIndicesFor;

getAtomsIndicesFor();
